name: Deploy AllStarsDiscordBot

env:
  BINARIES: './output/app_data/jobs/continuous/AllStarsDiscordBot'
  ZIP_FILE: 'DiscordBot.zip'
  ZIP_PATH: './output'
  ZIP_FILEPATH: './output/DiscordBot.zip'
  
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    environment:
      name: 'production'
       
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore ./AllstarsBot.sln
      
    - name: Publish
      run: dotnet publish ./AllstarsBot.sln -r win-x64 --self-contained false --configuration Release --no-restore --output ${{env.BINARIES}}
      
    - name: Zip
      uses: thedoctor0/zip-release@master
      with:
        filename: '${{env.ZIP_FILE}}'
        directory:  ${{ env.ZIP_PATH }}
        exclusions: '*.git* *.idea*' 
    
    - name: Deploy To Azure WebJobs
      uses: srijken/azure-zip-deploy@master
      with:
        zip-file: ${{ env.ZIP_FILEPATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A1813567FF604AB6899EA65C72F123C3 }}
        